var Case = [
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例一",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例二",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例三",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例四",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例五",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例六",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例七",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例八",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例九",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例十",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    }, {
        ContImg:'image/animate-12.jpg',
        title:"美美案例十一",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例十二",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例十三",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"美美案例十四",
        Icon1:'image/animate-13.jpg',
        Icon2:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },


]

var Item = [
    {
        ContImg:'image/animate-12.jpg',
        title:"项目动画一",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"项目动画二",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"项目动画三",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
        ContImg:'image/animate-12.jpg',
        title:"项目动画四",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"项目动画五",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"项目动画六",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"项目动画七",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"项目动画八",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"项目动画九",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"项目动画十",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"项目动画十一",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"项目动画十二",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"项目动画十三",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"项目动画十四",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
]


var Team = [
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画一",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画二",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画三",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画四",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画五",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画六",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画七",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画八",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画九",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画十",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画十一",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画十二",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画十三",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
    {
       ContImg:'image/animate-12.jpg',
        title:"团队动画十四",
        Icon1:'image/animate-13.jpg',
        Icon1:'image/animate-14.jpg',
        Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
        More:'More>>'
    },
]

